export const PRIVACY_POLICY = `
# Privacy Policy for IPA Master

**Last updated: ${new Date().toLocaleDateString()}**

At IPA Master, accessible from this application, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by IPA Master and how we use it.

## 1. Information We Collect

### Personal Information
We do not require you to create an account, nor do we store personal identifiable information (PII) such as your name, email address, or phone number on our servers.

### API Keys
If you choose to use the AI Pronunciation Assessment feature, you are required to provide a Google Gemini API Key.
*   **Storage:** Your API key is stored locally on your device using your browser's Local Storage (\`localStorage\`).
*   **Transmission:** Your API key is sent directly from your browser to Google's servers to authenticate your requests. It is **never** sent to or stored on IPA Master's servers.

### Audio Data
To use the pronunciation assessment feature, we require access to your device's microphone.
*   **Usage:** Audio recordings are captured solely for the purpose of analyzing your pronunciation.
*   **Processing:** These audio files are sent directly to the Google Gemini API for real-time analysis.
*   **Storage:** We do not permanently store your audio recordings. They are processed in memory and discarded after the analysis is complete.

## 2. Third-Party Services

### Google Gemini API
We use Google's Gemini API to provide pronunciation feedback. By using this feature, you acknowledge that your data (audio and API key) is processed by Google in accordance with their [Privacy Policy](https://policies.google.com/privacy) and [Terms of Service](https://policies.google.com/terms).

### Local Storage
We use local storage to save your preferences (such as your API key and UI settings). You can clear this data at any time by clearing your browser cache.

## 3. Log Files
IPA Master follows a standard procedure of using log files. These files log visitors when they visit websites. The information collected by log files includes internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.

## 4. Children's Information
We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. IPA Master does not knowingly collect any Personal Identifiable Information from children under the age of 13.

## 5. Consent
By using our website, you hereby consent to our Privacy Policy and agree to its terms.

---

If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.
`;

export const TERMS_OF_SERVICE = `
# Terms of Service

**Last updated: ${new Date().toLocaleDateString()}**

## 1. Introduction
Welcome to IPA Master! These terms and conditions outline the rules and regulations for the use of IPA Master's Website and Application. By accessing this website we assume you accept these terms and conditions. Do not continue to use IPA Master if you do not agree to take all of the terms and conditions stated on this page.

## 2. License
Unless otherwise stated, IPA Master and/or its licensors own the intellectual property rights for all material on IPA Master. All intellectual property rights are reserved. You may access this from IPA Master for your own personal use subjected to restrictions set in these terms and conditions.

You must not:
*   Republish material from IPA Master
*   Sell, rent or sub-license material from IPA Master
*   Reproduce, duplicate or copy material from IPA Master
*   Redistribute content from IPA Master

## 3. User Content (Audio)
In these Website Standard Terms and Conditions, "User Content" shall mean any audio, video text, images or other material you choose to display on this Website. By displaying Your Content, you grant IPA Master a non-exclusive, worldwide irrevocable, sub licensable license to use, reproduce, adapt, publish, translate and distribute it in any and all media.

However, as stated in our Privacy Policy, strictly for the functionality of this tool, **we do not store your audio content**.

## 4. Disclaimer
This tool is provided for educational purposes only.
*   **Accuracy:** While we strive for accuracy, the IPA symbols, examples, and AI-generated feedback may not be 100% accurate. Language and pronunciation can vary by region and dialect (this tool primarily focuses on RP/General British English).
*   **AI Feedback:** The pronunciation scores and feedback are generated by Artificial Intelligence (Google Gemini). These should be treated as a guide, not a professional linguistic assessment.
*   **"As Is" Basis:** The materials on IPA Master's website are provided on an 'as is' basis. IPA Master makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.

## 5. API Usage
You are responsible for managing your own Google Gemini API Key. IPA Master is not responsible for any costs incurred on your Google Cloud Platform account through the use of this tool.

## 6. Modifications
IPA Master is permitted to revise these Terms at any time as it sees fit, and by using this Website you are expected to review these Terms on a regular basis.

## 7. Governing Law
These Terms will be governed by and interpreted in accordance with the laws of the jurisdiction in which the creator resides, and you submit to the non-exclusive jurisdiction of the state and federal courts located in said jurisdiction for the resolution of any disputes.
`;
